// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "heteddy@126.com",
            "email": "heteddy@126.com"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/gateway-kit-svr/flow-gateway/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "end",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/gateway-kit-svr/flow-gw-details/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "服务名",
                        "name": "service",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/gateway-kit-svr/flow-service-details/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "服务名",
                        "name": "service",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/gateway-kit-svr/flow-services/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "end",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/gateway-kit-svr/gateway": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "gateway"
                ],
                "summary": "列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "gateway"
                ],
                "summary": "创建",
                "parameters": [
                    {
                        "description": "网关信息",
                        "name": "gw",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.GatewayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/gateway-kit-svr/gateway/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "gateway"
                ],
                "summary": "更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "网关id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "网关信息",
                        "name": "gw",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.GatewayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "gateway"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "网关id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/gateway-kit-svr/services": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "服务"
                ],
                "summary": "列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "服务"
                ],
                "summary": "创建",
                "parameters": [
                    {
                        "description": "服务信息",
                        "name": "gw",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.HttpSvcRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/gateway-kit-svr/services/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "服务"
                ],
                "summary": "列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服务id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "服务"
                ],
                "summary": "更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服务id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "服务信息",
                        "name": "gw",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.HttpSvcRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "服务"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服务id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "endpoint.GatewayRequest": {
            "type": "object",
            "required": [
                "allow_list",
                "block_list",
                "description",
                "name"
            ],
            "properties": {
                "allow_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "block_list": {
                    "description": "网关黑名单，所有的服务通用",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "description": "gateway name",
                    "type": "string"
                }
            }
        },
        "endpoint.HttpSvcRequest": {
            "type": "object",
            "required": [
                "addr",
                "allow_list",
                "block_list",
                "category",
                "client_qps",
                "description",
                "header_transfer",
                "is_https",
                "is_websocket",
                "match_rule",
                "name",
                "server_qps",
                "strip_uri",
                "url_rewrite"
            ],
            "properties": {
                "addr": {
                    "type": "string"
                },
                "allow_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "block_list": {
                    "description": "网关黑名单，所有的服务通用",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "category": {
                    "description": "0：url prefix 1: host   如果gateway绑定多个域名，可以通过访问的host，来进行重定向",
                    "type": "integer"
                },
                "client_qps": {
                    "description": "客户端流量控制",
                    "type": "integer"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "header_transfer": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "is_https": {
                    "type": "boolean"
                },
                "is_websocket": {
                    "type": "boolean"
                },
                "match_rule": {
                    "description": "匹配的项目与category结合使用，如果是domain，host==match_rule，否则是url前缀匹配",
                    "type": "string"
                },
                "name": {
                    "description": "gateway name",
                    "type": "string"
                },
                "server_qps": {
                    "description": "服务端流量控制",
                    "type": "integer"
                },
                "strip_uri": {
                    "description": "如果修改url可以通过gateway修改",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "url_rewrite": {
                    "description": "todo 需要支持正则表达式？,当修改了uri，可以对客户端保持兼容",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1",
	Host:        "localhost:9901",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "api-gateway 接口",
	Description: "api-gateway服务端接口",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
