name: gateway-kit
timeout: 3000  # 单位ms
version: v0.1.0
mode: debug
k8s: true
server:
  httpPort: 9901
  timeout: 4000 # 单位ms

redis:
  Addr: 192.168.64.5:6379
  Pass:
  Database: 3


gateway:
  httpPort: 9903
  grpcPort: 9904
  timeout: 4000 # 单位ms
  stripUri: gateway-kit
hystrix:


ratelimit:
  limit: 200  # 每秒产生多少token
  burst: 500  # 可以缓存的最大容量

mongoC:
  hosts: 192.168.64.5:27017,192.168.64.6:27017,192.168.64.7:27017
  user:
  pass:
  database: gateway
  replica: rs0

tables:   # 这里要创建不同的库，不能放到同一个库中
  httpSvc: tb_http_service
  grpcSvc: tb_grpc_service
  tcpSvc: tb_tcp_service
  gateway: tb_gateway
  serviceHour: tb_service_hour
  requestHour: tb_request_hour
  serviceDay: tb_service_day

kafkaEventProducer:
  broker:
  topics: topic_track_event
  clientID: gw_track_event_producer

