service: teddy-gateway
timeout: 3000
version: v0.1.0
mode: debug
server:
  httpPort: 9901
  timeout: 4000

gateway:
  httpPort: 9903
  grpcPort: 9904
  timeout: 4000
hystrix:


ratelimit:
  limit: 200  # 每秒产生多少token
  burst: 500  # 可以缓存的最大容量
